name: Summit Book Entry

on:
  repository_dispatch:
    types: [summit_book_entry]

jobs:
  create-entry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Entry File
      run: |
        mkdir -p entries
        echo "mountain: ${{ github.event.client_payload.mountain }}" > entries/entry_$(date +"%Y%m%d_%H%M%S").yml
        echo "climber: ${{ github.event.client_payload.climber }}" >> entries/entry_$(date +"%Y%m%d_%H%M%S").yml
        echo "date: ${{ github.event.client_payload.date }}" >> entries/entry_$(date +"%Y%m%d_%H%M%S").yml
        echo "comments: ${{ github.event.client_payload.comments }}" >> entries/entry_$(date +"%Y%m%d_%H%M%S").yml
        echo "timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> entries/entry_$(date +"%Y%m%d_%H%M%S").yml
    
    - name: Commit and Push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add entries/
        git commit -m "Add summit book entry"
        git push
